# Built using https://coral.withgoogle.com/tutorials/accelerator/
FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:latest

# Install python3
RUN install_packages python3-pip

# udev in the container to enable TPU correctly
ENV UDEV=1
COPY 99-tpu.rules /etc/udev/rules.d/99-tpu.rules

# Set our working directory
WORKDIR /usr/src/app

# Copy our models and source into the docker context
COPY src src
COPY images images
COPY run.sh run.sh

CMD ["bash","run.sh"]
